service: event-sourcing-example-ts-graphql-backend

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  stage: local
  runtime: nodejs20.x
  httpApi:
    cors: true

functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET