service: event-sourcing-example-ts-graphql-backend

plugins:
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-1
  stage: local
  runtime: nodejs20.x
  httpApi:
    cors: true

functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET

resources:
  Resources:
    #####################################
    # Journal Table
    #####################################
    JournalTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: journal
        AttributeDefinitions:
          - AttributeName: pkey
            AttributeType: S
          - AttributeName: skey
            AttributeType: S
          - AttributeName: aid
            AttributeType: S
          - AttributeName: seq_nr
            AttributeType: N
        KeySchema:
          - AttributeName: pkey
            KeyType: HASH
          - AttributeName: skey
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        GlobalSecondaryIndexes:
          - IndexName: journal-aid-index
            KeySchema:
              - AttributeName: aid
                KeyType: HASH
              - AttributeName: seq_nr
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10
        StreamSpecification:
          StreamViewType: NEW_IMAGE
          StreamEnabled: true

    #####################################
    # Snapshot Table
    #####################################
    SnapshotTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: snapshot
        AttributeDefinitions:
          - AttributeName: pkey
            AttributeType: S
          - AttributeName: skey
            AttributeType: S
          - AttributeName: aid
            AttributeType: S
          - AttributeName: seq_nr
            AttributeType: N
        KeySchema:
          - AttributeName: pkey
            KeyType: HASH
          - AttributeName: skey
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        GlobalSecondaryIndexes:
          - IndexName: snapshot-aid-index
            KeySchema:
              - AttributeName: aid
                KeyType: HASH
              - AttributeName: seq_nr
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10

custom:
  serverless-dynamodb:
    stages:
      - local
    start:
      docker: true
      port: 18000
      host: 127.0.0.1
      inMemory: true
      migrate: true
      seed: false
      convertEmptyValues: true
      noStart: true