service: event-sourcing-example-ts-graphql-backend

plugins:
  - serverless-esbuild
  - serverless-offline-dynamodb-streams
  - serverless-dynamodb
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-1
  stage: local
  runtime: nodejs20.x
  httpApi:
    cors: true

functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
  projector:
    handler: src/projector-server.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ JournalTable, StreamArn ]

resources:
  Resources:
    #####################################
    # Journal Table
    #####################################
    JournalTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: journal
        AttributeDefinitions:
          - AttributeName: pkey
            AttributeType: S
          - AttributeName: skey
            AttributeType: S
          - AttributeName: aid
            AttributeType: S
          - AttributeName: seq_nr
            AttributeType: N
        KeySchema:
          - AttributeName: pkey
            KeyType: HASH
          - AttributeName: skey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: journal-aid-index
            KeySchema:
              - AttributeName: aid
                KeyType: HASH
              - AttributeName: seq_nr
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_IMAGE
          StreamEnabled: true

    #####################################
    # Snapshot Table
    #####################################
    SnapshotTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: snapshot
        AttributeDefinitions:
          - AttributeName: pkey
            AttributeType: S
          - AttributeName: skey
            AttributeType: S
          - AttributeName: aid
            AttributeType: S
          - AttributeName: seq_nr
            AttributeType: N
        KeySchema:
          - AttributeName: pkey
            KeyType: HASH
          - AttributeName: skey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: snapshots-aid-index
            KeySchema:
              - AttributeName: aid
                KeyType: HASH
              - AttributeName: seq_nr
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

custom:
  serverless-dynamodb:
    stages:
      - local
    start:
      docker: true
      port: 18000
      host: 127.0.0.1
      inMemory: true
      migrate: true
      seed: false
      convertEmptyValues: true
      noStart: true
  serverless-offline-dynamodb-streams:
    apiVersion: '2013-12-02'
    endpoint: http://127.0.0.1:18000
    region: ap-northeast-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    readInterval: 500