version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: es-example-ts.event-store.local
    ports:
      - "18000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: es-example-ts.dynamodb-admin.local
    ports:
      - "18001:8001"
    environment:
      DYNAMO_ENDPOINT: dynamodb-local:8000
      AWS_DEFAULT_REGION: ap-northeast-1
    depends_on:
      - dynamodb-local
